#' @section Utility function for parsing metrics output:
#'   Formats metrics data from the current query
#' @param x A data frame generated by Prometheus query
#' @rdname utilities

format_metrics_instant_data <- function(x) {

  within(data = x,
         expr = {
           port = as.integer(gsub(
             pattern = "(.*):(.*)",
             replacement = "\\2",
             x = instance
           ))

           instance = gsub(pattern = "(.*):(.*)",
                           replacement = "\\1",
                           x = instance)

           value = trimws(as.integer(value))
         })
}


#' @section Utility function for parsing range metrics output:
#'   Formats metrics data passed by range query.
#' @rdname utilities
format_metrics_range_data <- function(x) {
  checkmate::assert_data_frame(x = x,
                               min.rows = 1,
                               min.cols = 2)
  x_metrics <- within(data = x$metric,
         expr = {
           port = as.integer(gsub(
             pattern = "(.*):(.*)",
             replacement = "\\2",
             x = instance
           ))

           instance = gsub(pattern = "(.*):(.*)",
                           replacement = "\\1",
                           x = instance)
         })

  dfs_to_bind <- lapply(
    X = x$values,
    FUN = function(value_pair) {
      setNames(object = as.data.frame(value_pair),
               nm = c("timestamp", "value")) -> df_ts_val
    }
  )

  i <- 1
  Reduce(rbind,
         lapply(
           X = dfs_to_bind,
           FUN = function(dfs) {
             x <- suppressWarnings(cbind(x_metrics[i, ], dfs))
             i <<- i + 1
             x
           }
         )) -> res

  return(res)
}
