#' @section Utility function for parsing metrics output:
#'   Formats metrics data from the current query
#' @param x A data frame generated by Prometheus query
#' @rdname utilities

format_metrics_current_data <- function(x) {
  # Check if passed object is a data frame of required characteristics
  checkmate::assert_data_frame(x = x,
                               min.rows = 1,
                               min.cols = 5)

  within.data.frame(data = setNames(
    object = x,
    nm = c("metric", "instance", "job", "timestamp", "value")
  ),
  expr = {
    port = as.integer(gsub(pattern = "(.*):(.*)",
                replacement = "\\2",
                x = instance))

    instance = gsub(pattern = "(.*):(.*)",
                    replacement = "\\1",
                    x = instance)

    value = trimws(as.integer(value))
  })
}


#' @section Utility function for parsing range metrics output:
#'   Formats metrics data passed by range query.
#' @rdname utilities
format_metrics_range_data <- function(x) {
  return(x)
}
